language: rust
env:
  global:
    - secure: LrKOXMj+T3fZ6v7o6VkS2wUeHXeqRF5OX00/WrUOPrUoK9RoTlNBPIgShsf1PMcCyVQhqtzVRJkTh/0SeZMmdfXUsO9fNiffqxDhjOdGUIHWrhIzFFlIjEvsbJYq8D+353B90ZzWajSu5uz9zsnytBxj4FDjIRXOi2tYt+jmmyY=
script:
  - cargo build
  - rustdoc -L target/deps src/k8055.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh    
