[package]

name = "k8055"
version = "0.0.1"
authors = ["hirschen <falco.hirschenberger@itwm.fraunhofer.de>"]

[lib]

name = "k8055"

[dependencies.usb]

git = "https://github.com/kevinmehall/rust-usb"
