[package]

name = "k8055"
version = "0.0.4"
authors = ["hirschen <falco.hirschenberger@itwm.fraunhofer.de>"]
description = "Rust support for the Vellemann K8055 USB IO Card"
homepage = "https://github.com/hirschenberger/k8055.rs"
repository = "https://github.com/hirschenberger/k8055.rs.git"
readme = "README.md"
keywords = ["hardware", "usb", "IO"]
license = "GPL-2.0"

[lib]

name = "k8055"

[dependencies]

usb = "~0.1.0"
